spring:
  profiles:
    active: local #local, dev, real (설정 환경)

  datasource: #db 설정
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: user01
    password: 1234
    hikari:
      connection-timeout: 30000 #클라이언트가 pool에 커넥션을 요청하는데 기다리는 최대시간을 설정 30초
      maximum-pool-size: 10 #최대 커넥션 개수 설정
      max-lifetime: 1800000 #커넥션 풀에서 살아있을 수 있는 커넥션의 최대 수명 시간 1,800초(30분)
      
  messages: #메세지 처리
    basename: messages.validation
    encoding: utf-8
    
  devtools: #View reload
    livereload:
      enabled: true
    
    restart: #컨트롤러, 모델단이 바뀌었을 때 프로젝트 재시작 설정(정확히 classpath(src)에 있는 모든 파일이 변경될 시 재시작)
      enabled: true
      
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    enabled: true
    mode: HTML5
    cache: false #캐시 사용하지 않음. 새로고침하면 변경사항이 바로 반영되도록
    
mybatis:
  type-aliases-package: kr.spring.**.vo
  mapper-locations: kr/spring/**/dao/*.xml
  
logging:
  level:
#    root: error
    '[kr.sring]': debug
    
server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true #http 인코딩 지원을 활성화할지 여부
      force: true