CREATE TABLE semployee(
	num NUMBER PRIMARY KEY,
	id VARCHAR2(12) UNIQUE NOT NULL,
	name VARCHAR2(30) NOT NULL,
	passwd VARCHAR2(12) NOT NULL,
	salary NUMBER(8) NOT NULL,
	job VARCHAR2(30) NOT NULL,
	reg_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE semployee_seq;