CREATE TABLE dailynews(
	num NUMBER PRIMARY KEY,
	title VARCHAR2(150)	NOT NULL,
	writer VARCHAR2(30) NOT NULL,
	passwd VARCHAR2(12) NOT NULL,
	email VARCHAR2(50) NOT NULL,
	article CLOB NOT NULL,
	filename VARCHAR2(400) NOT NULL,
	reg_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE dailynews_seq;