-- MVC 게시판
CREATE TABLE svboard(
	num NUMBER PRIMARY KEY,
	title VARCHAR2(150) NOT NULL,
	name VARCHAR2(30) NOT NULL,
	passwd VARCHAR2(12) NOT NULL,
	email VARCHAR2(50) NOT NULL,
	content CLOB NOT NULL,
	ip VARCHAR2(30) NOT NULL,
	reg_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE svboard_seq;